# Generated by Django 4.2.5 on 2023-09-27 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('user', models.CharField(max_length=30, verbose_name='user')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
