# Generated by Django 4.2.5 on 2023-09-30 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda'), ('3', 'Terca'), ('1', 'Quarta'), ('2', 'Quinta'), ('3', 'Sexta'), ('7', 'Sabado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medcine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount_consumed', models.SmallIntegerField()),
                ('initial_amount', models.SmallIntegerField()),
                ('actual_amount', models.SmallIntegerField()),
                ('purchase_date', models.DateField()),
                ('end_date', models.DateField()),
                ('consumption', models.ManyToManyField(to='cloudpharma.choice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
