# Generated by Django 4.1.12 on 2023-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudpharma', '0003_alter_medcine_actual_amount_alter_medcine_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda'), ('3', 'Terca'), ('1', 'Quarta'), ('2', 'Quinta'), ('3', 'Sexta'), ('7', 'Sabado')], max_length=50, unique=True),
        ),
    ]
